HakanBilgisayar/HakanBilgisayar/Controllers/TeknikServisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HakanBilgisayar.Controllers
{
    public class TeknikServisController : Controller
    {
        // GET: TeknikServis
        public ActionResult Index()
        {
            return View();
        }
    }
}

HakanBilgisayar/HakanBilgisayar/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <!--Css Dosyaları-->
    <link href="/Content/font-awesome.min.css" rel="stylesheet">
    <link href="/Content/prettyPhoto.css" rel="stylesheet">
    <link href="/Content/price-range.css" rel="stylesheet">
    <link href="/Content/animate.css" rel="stylesheet">
    <link href="/Content/main.css" rel="stylesheet">
    <link href="/Content/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <!--İmages Dosyaları-->
    <link rel="shortcut icon" href="/Content/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/Content/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/Content/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/Content/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/Content/images/ico/apple-touch-icon-57-precomposed.png">


</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Anasayfaya Dön", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Slider", "Slider", "Admin")</li>
                    <li>@Html.ActionLink("Bilgisayar", "Bilgisayar", "Admin")</li>
                    <li>@Html.ActionLink("Elektronik", "Elektronik", "Admin")</li>
                    <li>@Html.ActionLink("Yazıcı", "Yazici", "Admin")</li>
                    
                </ul>
                <div class="nav navbar-nav navbar-right col-md-4">
                    <div class="col-md-3">
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle navbar-btn" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">TR <span class="caret"></span></button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="#">EN</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input-group">
                            <input type="text" class="navbar-form form-control" placeholder="Arama...">
                            <span class="input-group-btn">
                                <button class="btn btn-default navbar-btn" type="button">Ara</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <br />
        <br />
        <br />
        <br />
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>Admin Paneli</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    @RenderSection("scripts", required: false)
    <hr />
    </div>
</body>
</html>

HakanBilgisayar/HakanBilgisayar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <!--Css Dosyaları-->
    <link href="/Content/font-awesome.min.css" rel="stylesheet">
    <link href="/Content/prettyPhoto.css" rel="stylesheet">
    <link href="/Content/price-range.css" rel="stylesheet">
    <link href="/Content/animate.css" rel="stylesheet">
    <link href="/Content/main.css" rel="stylesheet">
    <link href="/Content/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <!--İmages Dosyaları-->
    <link rel="shortcut icon" href="/Content/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/Content/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/Content/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/Content/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/Content/images/ico/apple-touch-icon-57-precomposed.png">


</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("HAKAN Bilgisayar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ürünler <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li>@Html.ActionLink("Bilgisayarlar", "Index", "Home")</li>
							<li>@Html.ActionLink("Elektronik" , "Elektronik", "Home")</li>
							<li>@Html.ActionLink("Yazıcı", "Yazici", "Home")</li>
						</ul>
					</li>
					<li>@Html.ActionLink("Teknik Servis", "Index", "TeknikServis")</li>
					<li>@Html.ActionLink("Hakkımızda", "Contact", "Home")</li>
					<li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
					
				</ul>
				<div class="nav navbar-nav navbar-right col-md-4">
					<div class="col-md-3">
						<div class="dropdown">
							<button class="btn btn-default dropdown-toggle navbar-btn" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">TR <span class="caret"></span></button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">EN</a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-6">
						<div class="input-group">
							<input type="text" class="navbar-form form-control" placeholder="Arama...">
							<span class="input-group-btn">
								<button class="btn btn-default navbar-btn" type="button">Ara</button>
							</span>
						</div>
					</div>
				</div>
				@Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
			</div>
		</div>
	</div>
    <div class="container">
        <br />
        <br />
        <br />
        <br />
        <br />
        @RenderBody()
        <hr />
        <footer>
            <div class="header_top">
                <!--header_top-->
                <div class="container">
                    <div class="row">
                        <div class="col-sm-3">
                            @Html.ActionLink("HAKAN Bilgisayar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        </div>
                        <div class="col-sm-4 dl-horizontal">
                                &copy; @DateTime.Now.Year - My ASP.NET Application
                        </div>                         
                            <div class="col-sm-5">
                                <div class="contactinfo text-center col-sm-5">
                                    <ul class="nav navbar-nav">
                                        <li><a href=""><i class="fa fa-phone"></i> +90 555 55 55</a></li>
                                    </ul>
                                </div>
                              <div class="social-icons text-center col-sm-7">
                                    <ul class="nav navbar-nav">
                                       <li><a href="https://www.facebook.com/TnyKnc"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="https://twitter.com/TnyKnc"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href=""><i class="fa fa-linkedin"></i></a></li>
                                        <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                                        <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                    </div>
                </div>
            </div>         
</footer>
    </div>        
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")

                
        @RenderSection("scripts", required: false)
        <hr />
    </div>
</body>
</html>